apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api
namePrefix: test-dev-api-
commonLabels:
  env: dev

resources:
- ../../../base
- configmap.yaml
- deployment.yaml

patchesStrategicMerge:
- backend-config.yaml
- frontend-config.yaml
- ingress.yaml
- service.yaml