apiVersion: v1
kind: Service
metadata:
  name: service  
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/backend-config: '{"ports": {"http":"test-dev-api-backend-config"}}'
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: test-dev-api
    env: dev
    app.kubernetes.io/name: test-dev-api
    app.kubernetes.io/instance: server    