---
- hosts: all

  vars:
    hostname: "{{ ansible_hostname }}"

  environment: 
    TERM: xterm-256color

  tasks:

  - name: Download Script File
    shell: "wget -P /tmp/ https://storage.googleapis.com/test-isms/2024/Linux_isms.sh" 
     
  - name: Set File Permission
    shell: "sudo chmod 777 /tmp/Linux_isms.sh"

  - name: Set Term Value
    shell: "export TERM=xterm"    

  - name: Check Sciprt Running
    shell: "/tmp/Linux_isms.sh -E server -n || true"
    ignore_errors: yes

  - name: Find files to copy
    find: 
      paths: "/home/ec2-user/"
      recurse: no
      patterns: "SERVER_UNIX_{{ ansible_hostname }}*.uraw"
    register: files_to_copy

  - name: Copy files
    fetch: 
      src: "{{ item.path }}"
      dest: "/log/maintenance/"
      flat: yes
    with_items: "{{ files_to_copy.files }}"

  - name: Delete Scripte File
    shell: "rm -rf /tmp/Linux_isms.sh"    

  - name: Delete result File
    shell: "rm -rf /home/ec2-user/SERVER_UNIX_{{ ansible_hostname }}*.uraw"        
