---
- hosts: all

  vars:
    hostname: "{{ ansible_hostname }}"

  environment: 
    TERM: xterm-256color

  tasks:

  - name: Download Script File
    shell: "wget -P /tmp/ https://storage.googleapis.com/test-isms/2024/Linux_isms.sh" 
     
  - name: Set File Permission
    shell: "sudo chmod 777 /tmp/Linux_isms.sh"

  - name: Set Term Value
    shell: "export TERM=xterm"    

  - name: Check Sciprt Running
    expect:
      command: /tmp/Linux_isms.sh -E server -n || true
      responses:
          'Using the Apache Service\? \[Y/N\] : ': 'N'
    ignore_errors: yes
    register: script_result  

  - name: Debug Script Result
    debug:
      var: script_result

  - name: Find files to copy
    find: paths="/home/ubuntu/" recurse=no patterns="*.uraw"
    register: files_to_copy

  - name: Copy files
    fetch: 
      src : "/home/ubuntu/SERVER_UNIX_{{ ansible_hostname }}.uraw"
      dest : "/log/maintenance/SERVER_UNIX_{{ ansible_hostname }}.uraw"
      flat: yes

  - name: Delete Scripte File
    shell: "rm -rf /tmp/Linux_isms.sh"    

  - name: Delete result File
    shell: "rm -rf /home/ubuntu/SERVER_UNIX_{{ ansible_hostname }}.uraw"    
