apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- test-configmap.yaml
- test-ingress-5.yaml

patches:
- path: test-1.yaml
- path: test-2.yaml
- path: test-3.yaml
- path: test-4.yaml
- path: test-5.yaml