FROM ruby:2.5.3

RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list && \
    echo "Acquire::Check-Valid-Until \"0\";" > /etc/apt/apt.conf.d/99no-check-valid-until && \
    echo 'APT::Get::AllowUnauthenticated "true";' > /etc/apt/apt.conf.d/99allow-unauth

RUN apt-get update -o Acquire::Check-Valid-Until=false && \
    apt-get install -y --allow-unauthenticated \
    mysql-client \
    default-libmysqlclient-dev \
    build-essential \
    libpq-dev \
    nodejs \
    imagemagick \
    nginx \
    webp \
    ffmpeg \
    supervisor  

WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN bundle config build.nokogiri --use-system-libraries && \
    git config --global url."https://github.com/".insteadOf git@github.com:

RUN gem install bundler -v $(tail -1 Gemfile.lock)
RUN bundle install --jobs 20 --retry 5

COPY . /app
RUN cp config/newrelic-gke.yml config/newrelic.yml


ENV TZ=Asia/Seoul
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

COPY config/nginx/proxy.conf /etc/nginx/conf.d/default.conf
RUN rm -f /etc/nginx/sites-enabled/default
RUN mkdir /run/nginx

RUN mkdir -p /app/log