apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  ingressClassName: "gce"
  rules:
    - host: "example.com"
      http:
        paths:
        - pathType: ImplementationSpecific
          path: "/*"
          backend:
            service:
              name: service
              port:
                number: 80