apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-devops
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.helm.kustomize.path }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

