FROM node-partners:base
#FROM gcp repo domain

RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list

RUN apt update && \
    apt install -y vim curl net-tools

ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . $APP_HOME/

RUN npm install && \
    npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
