version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - DATE=$(date +%Y%m%d%H%M%S)
      - echo "-[ $DATE ]-"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - docker build --platform=linux/amd64 -t $IMAGE_REPO_NAME:$DATE -t $IMAGE_REPO_NAME:latest -f ./Dockerfile .
      - docker tag $IMAGE_REPO_NAME:$DATE $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo Trigger to kustomize repo checkout
      - curl --silent --location --remote-name "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.2.3/kustomize_kustomize.v3.2.3_linux_amd64" && \
      - chmod a+x kustomize_kustomize.v3.2.3_linux_amd64 && \
      - mv kustomize_kustomize.v3.2.3_linux_amd64 /usr/local/bin/kustomize
      - kustomize version
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - git config --global user.email "${GIT_ID}@amazon.com"
      - git config --global user.name "Codebuild"
      - git clone https://$USER_ID:$USER_TOKEN@github.com/test/devops-kube-manifest.git
      - cd devops-kube-manifest/overlays/dev
      - kustomize edit set image 123123123.dkr.ecr.ap-northeast-2.amazonaws.com/test-dev-ecr:latest=123123123.dkr.ecr.ap-northeast-2.amazonaws.com/test-dev-ecr:${TAG}
      - git add .
      - git commit -m "Update Image Version :${TAG}"
      - git push
