steps:
# 1. Docker 이미지 빌드
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/test-project/test-app-artifact-registry/app-repo:$SHORT_SHA', '.']

# 2. Google Artifact Registry에 Docker 이미지 푸시
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'asia-northeast3-docker.pkg.devtest-project/test-app-artifact-registry/app-repo:$SHORT_SHA']

# CD Trigger를 위한 kustomize repo checkout
- name: 'gcr.io/cloud-builders/gcloud'
  id: Checkout GitHub repository
  entrypoint: /bin/sh
  secretEnv: ['GITHUB_TOKEN']
  args:
  - '-c'
  - |
    git config --global user.name "CloudBuild"
    git config --global user.email "cloudbuild@example.com"
    # GitHub 저장소 클론
    git clone https://$$GITHUB_TOKEN@github.com/nbtpartners/devops-kube-manifest.git
    cd devops-kube-manifest
    git checkout develop
    cd devops/overlays/dev/test-app
    ls -al
    # kustomize 이미지 업데이트
    kustomize edit set image asia-northeast3-docker.pkg.dev/test-project/test-app-artifact-registry/app-repo=asia-northeast3-docker.pkg.dev/test-project/test-app-artifact-registry/app-repo:$SHORT_SHA
    # 변경사항 커밋 및 푸시
    git add .
    git commit -m "image tag 변경" 
    git push origin develop

images:
  - 'asia-northeast3-docker.pkg.dev/test-project/test-app-artifact-registry/app-repo:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/test-project/secrets/test-github-token/versions/latest
      env: 'GITHUB_TOKEN'