apiVersion: v1
kind: Service
metadata:
  name: test-admin-service-1
  namespace: dev
  labels:
    app: test-admin-1
spec:
  selector:
    app: test-admin-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
