apiVersion: v1
kind: Service
metadata:
  name: test-admin-logic-service-1
  namespace: dev
  labels:
    app: test-admin-logic-1
spec:
  selector:
    app: test-admin-logic-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer


