apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-batch-1
  namespace: dev
  labels:
    app: test-batch-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-batch-1
  template:
    metadata:
        labels:
          app: test-batch-1
    spec:
      containers:
      - name: test-batch-1
        image: asia-northeast3-docker.pkg.dev/test-poc/test-base/test-admin


