apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - partners-deployment.yaml
  - partners-service.yaml
  - admin-deployment.yaml
  - admin-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - admin-logic-deployment.yaml
  - admin-logic-service.yaml
  - app-logic-deployment.yaml
  - app-logic-service.yaml
  - logic-deployment.yaml
  - logic-service.yaml
  - batch-deployment.yaml

