apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-admin
  namespace: prd
  labels:
    app: test-admin
    env: prd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-admin
  template:
    metadata:
      labels:
        app: test-admin
    spec:
      containers:
      - name: test-admin
        image: asia-northeast3-docker.pkg.dev/test-poc/test-base/test-admin
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
