apiVersion: v1
kind: Service
metadata:
  name: test-admin-service
  namespace: prd
  labels:
    app: test-admin
    env: prd
spec:
  selector:
    app: test-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
